### PR TITLE
rework of the error handling

### PR DESCRIPTION
**Pull request by jannik-hh**
add more specific error classes
 access the entire response from the error object
 access the error descriptions directly from the error object

### CODE REVIEW

**Comment by bvogel** [comment]
Hi @sfroehler - any reason why this wasn't included in the 0.6.0 release? This was the most interesting part to us!

**Comment by sfroehler** [comment]
Hi @bvogel

It was not included because this is a breaking change and we needed a release with the remaining changes.
A release including this PR will follow later today.

**Comment by bvogel** [comment]
:smile: :+1:

**Comment by sfroehler** [comment]
ready to merge

**Comment by bvogel** [comment]
Now I'm confused - as per SemVer I would have expected this to go into a mayor release (as it is breaking?)

**Comment by sfroehler** [comment]
From semver.org:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> (http://semver.org/#spec-item-4)

As I mentioned before we did a separate release to make the remaining changes available without introducing a breaking change.

**Comment by bvogel** [comment]
Thanks for clearing that up - so when is v1.0.0 to be expected? :)

**Pull request merged**
