### PR TITLE
Parse response only when it's not empty

### PR DESCRIPTION
**Pull request by oiuzikov**
Previously, 

``` ruby
Shipcloud::Shipment.delete <id>
```

caused TypeError converting nil to String

### CODE REVIEW

**Comment by sfroehler** [comment]
Hi @oleksandriuzikov,

thank you for your contribution and the bugfix! :+1: 

Could you please add a test and a comment under the _Unreleased_ -> _Fixed_ headline in the [changelog](https://github.com/shipcloud/shipcloud-ruby/blob/master/CHANGELOG.md)?
That would be awesome!

**Comment by sfroehler** [comment]
hey @oiuzikov. Thanks again for this PR.

Any chance you could add a test to document the bugfix?

**Comment by oiuzikov** [comment]
@sfroehler good point. I'll add a test. Thanks

**Comment by sfroehler** [comment]
Merged to master with 29ef40e7f025d970ad1bb4d9d15cb15193f7b59f

**Pull request closed without merging**
