### PR TITLE
Add attr_reader :customs_declaration

### PR DESCRIPTION
**Pull request by matiasalbarello**

### CODE REVIEW

**Comment by sfroehler** [comment]
Hi @matiasalbarello,
thanks for your contribution! 
I have updated a few config files on master so it would be very kind if you got merge or rebase on current master.

**Comment by sfroehler** [comment]
Thanks for rebasing, @matiasalbarello. 👍 
Hound found two violations. Once they have been fixed I'm happy to merge.

**Comment by matiasalbarello** [comment]
The violations are not related with the code of this feature. It is related with the changes imported with the rebasing. I will create a new PR

**Comment by sfroehler** [comment]
> The violations are not related with the code of this feature. It is related with the changes imported with the rebasing. I will create a new PR

@matiasalbarello, I was talking about these comments:

https://github.com/shipcloud/shipcloud-ruby/pull/34/files#r244946128
https://github.com/shipcloud/shipcloud-ruby/pull/34/files#r244946127

**Comment by matiasalbarello** [comment]
Sorry, I misunderstood the Hound.

**Comment by sfroehler** [comment]
> Sorry, I misunderstood the Hound.

No worries - I should have been more specific in my previous message.
Looks good now! Thanks again. 👍

**Review by sfroehler — APPROVED** [review]

**Comment by matiasalbarello** [comment]
Thanks!

**Pull request merged**
