### PR TITLE
Add basic operations for webhooks resource

### PR DESCRIPTION
**Pull request by dorotheelaugwitz**
- Adds a webhook resource
- Adds calls for creating, listing and finding webhook resources

### CODE REVIEW

**Comment by sfroehler** [comment]
@DorotheeLaugwitz could you please update the [Changelog](../blob/master/CHANGELOG.md) and state what you changed? You need to do a rebase on the current master to get the new Changelog first.

**Comment by bvogel** [comment]
Is there a release planned soonish? We are very interested in the error handling improvement

**Comment by sfroehler** [comment]
Hey @bvogel - yes there is a release planned for next weak - probably multiple releases as the change regarding the error handling is a breaking change.

**Comment by dorotheelaugwitz** [comment]
@sfroehler The changelog is now updated

**Comment by sfroehler** [comment]
Thanks @DorotheeLaugwitz

**Pull request merged**
