### PR TITLE
Add `Tracker` resource with create, find, and index operations

### PR DESCRIPTION
**Pull request by jungbunzlav**
Adds the new `Tracker` resource the gem. The operations create,
find, and index are supported.

Further Information on shipcloud's Trackers
https://developers.shipcloud.io/reference/#trackers

### CODE REVIEW

**Comment by jungbunzlav** [comment]
[Affiliate-ID im Request-Header mitgeben, wenn konfiguriert](https://trello.com/c/nxvamF2P/12-affiliate-id-im-request-header-mitgeben-wenn-konfiguriert)

**Comment by jungbunzlav** [comment]
[Tracker Ressource hinzufügen](https://trello.com/c/7Jr4TzEr/13-tracker-ressource-hinzuf%C3%BCgen)

**Review by sfroehler — APPROVED** [review]
ready to merge

**Comment by sfroehler** [comment]
ready to merge

**Pull request merged**
